// METHODS TO ADD LATER
// Add data
//   let obj = {
//     name: "VIKING",
//     age: 25,
//   };
//   firebase.database().ref("STUDENTS/VIKINGS").set(obj);

//   // // read data
//   firebase
//     .database()
//     .ref(
//       "STUDENTS/TITANS/Aaron Lovelace Nana Kwasi Abayie PREMPEH/0/streak"
//     )
//     .on("value", (sanpshot) => {
//       console.log(sanpshot.val());
//     });

//   // update data
//   let newupdateddata = {
//     lateness: 1,
//     streak: 2,
//   };
//   firebase
//     .database()
//     .ref("STUDENTS/TITANS/Aaron Lovelace Nana Kwasi Abayie PREMPEH/0")
//     .update(newupdateddata);

//   // remove data
//   firebase.database().ref("users/user3").remove();
